#on: [push, pull_request]
on: [pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        #go-version: [1.13.x, 1.14.x]
        go-version: [1.14.x]
        #platform: [ubuntu-latest, macos-latest, windows-latest]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Unit Test
        run: go test -race $(go list ./... | grep -v integration_tests)
      - name: Integration Test
        run: go test -race ./integration_tests/...